---

- name: 'Configure SumoCollector'
  template:
    src: sumo.conf.j2
    dest: /etc/sumo.conf
  register: sumologic_collector_add_configuration
  tags: sumologic
  notify: Restart SumoCollector

- name: 'Create collector configuration'
  template:
    src: collector.json.j2
    dest: /etc/sumologic-collector.json
  tags: [sumologic, sumologic-collector]
  notify: Restart SumoCollector

- include: linux_performance.yml
  tags: sumologic
  when: sumologic_do_sysstat | default(False)

- name: 'Force restart SumoCollector'
  shell: /usr/local/SumoCollector/collector restart
  tags: [sumologic, sumologic-collector, sumologic_force_restart]
  when: sumologic_force_restart == "yes"

- include: native_install.yml
  when: sumologic_install_method == "native"

- include: docker_install.yml
  when: sumologic_install_method == "docker"
