---
- name: install mesos packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mesos_package }}"
    - cyrus-sasl-md5
  tags:
    - mesos
    - bootstrap

- name: ensure consul.d is present
  sudo: yes
  file:
    path: "{{ consul_dir }}"
    state: directory
  tags:
    - mesos

- name: configure mesos-log-cleanup cron job
  sudo: yes
  copy:
    src: mesos-log-cleanup
    dest: /etc/cron.hourly/mesos-log-cleanup
    owner: root
    group: root
    mode: 0755
  tags:
    - mesos

- include: leader.yml
  when: mesos_mode == "leader" or mesos_mode == "mixed"

- include: follower.yml
  when: mesos_mode == "follower" or mesos_mode == "mixed"
