---
- name: install mantl-dns
  sudo: yes
  yum:
    name: "mantl-dns-{{ mantl_dns_version }}"
    state: latest
  tags:
    - dnsmasq
    - bootstrap

- name: configure dnsmasq for Kubernetes
  sudo: yes
  template:
    src: 20-kubernetes
    dest: /etc/dnsmasq.d/20-kubernetes
    mode: 0755
  when: cluster_name is defined
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- meta: flush_handlers

- include: distributive.yml
