# c12e_customize.yml

- hosts: all
  sudo: yes
  vars: 
    # a directory where you keep configuration of mantl projects
    mantl_config_dir: ~/projects/mantl-config
    wildcard_certs_dir: "{{mantl_config_dir}}/example.com.certs"
    use_wildcard_certs: "yes"
  tasks:
    - debug: msg="{{mantl_config_dir}}"

    - name: install some basics
      yum:
        name: "{{item}}"
      with_items:
        - nano
        - telnet


    - include: wildcard_ssl.yml
      when: (use_wildcard_certs == 'yes')

# These are touch-ups for special cases.
# should be templatized on wildcard cert names.

    # - name: concatenate CA and wildcard.cert for traefik
    #   sudo: yes
    #   shell: cat /public_certs/wildcard.c1.io.cert.pem /public_certs/geoTrust_CA_Chain.cert.pem  > /public_certs/wildcard-chain.c1.io.cert.pem

    # - name: concatenate private key with cert for mongo
    #   sudo: yes
    #   shell: cat /private_certs/container.key.pem /public_certs/container.cert.pem > /private_certs/mongo.container.key.pem
    #   when: inventory_hostname in groups['role=worker']

    # - name: concatenate CA and container.cert for mongo
    #   sudo: yes
    #   shell: cat /public_certs/container.cert.pem /public_certs/ca.cert.pem > /public_certs/ca-chain.cert.pem
    #   when: inventory_hostname in groups['role=worker']


